export const authConstants ={
      LOGIN_REQUEST:'LOGIN_REQUEST',
      LOGIN_FAILURE:'LOGIN_FAILURE',
      LOGIN_SUCCESS:'LOGIN_SUCCESS'
}

export const userConstants= {
      REGISTER_REQUEST:'REGISTER_REQUEST',
      REGISTER_FAILURE:'REGISTER_FAILURE',
      REGISTER_SUCCESS:'REGISTER_SUCCESS'
}
export const categoryConstants= {
     CATEGORY_REQUEST:"CATEGORY_REQUEST",
     CATEGORY_FAILURE:"CATEGORY_FAILURE,",
     CATEGORY_SUCCESS:"CATEGORY_SUCCESS",
     ADD_CATEGORY_REQUEST:"ADD_CATEGORY_REQUEST",
     ADD_CATEGORY_FAILURE:"ADD_CATEGORY_FAILURE,",
     ADD_CATEGORY_SUCCESS:"ADD_CATEGORY_SUCCESS",

}
export const productConstants= {
      PRODUCT_GET_REQUEST:"PRODUCT_GET_REQUEST",
      PRODUCT_GET_FAILURE:"PRODUCT_GET_FAILURE,",
      PRODUCT_GET_SUCCESS:"PRODUCT_GET_SUCCESS",
      PRODUCT_POST_REQUEST:"PRODUCT_POST_REQUEST",
      PRODUCT_POST_FAILURE:"PRODUCT_POST_FAILURE,",
      PRODUCT_POST_SUCCESS:"PRODUCT_POST_SUCCESS",
 
 }